### ISSUE TITLE
Check-in

### ISSUE THREAD

**Issue by trebird** [trebird/animal-rescue-website#1]
Hi @charlie-quinn,

Unfortunately my _end of day_ Friday lasted until _beginning of day_ Saturday, so completely understand if this means eating those grades, but wanted to send an update anyway and happy to report it's been a fun/relatively painless process adding content and style to the pages.

Will still need to finish adding content, figure out weird quirks (see hilarious contact button in adopt.html nav!), and plenty more, but here's where I'm at so far.

Hope you have a great weekend!

**Comment by trebird** [comment]
Another note, I just tried the site through the github link and it looks like something crazy is happening with the styling or CSS links or something else.

Concerning...will have to investigate

**Comment by charlie-quinn** [comment]
I'll take a look at this later tonight. 👌👀

**Comment by charlie-quinn** [comment]
Thanks @trebird it's starting to look great! The only thing I noticed right away was your form – it will need to be longer, feel free to pull copy from the existing one (although, be careful not to  make it _too loong_). 👍

**Comment by charlie-quinn** [comment]
⚠️`Reminder: please close this issue once it has been resolved.`

**Comment by trebird** [comment]
Thanks Charlie! Will keep working on it!
