### ISSUE TITLE
Submission

### ISSUE THREAD

**Issue by trebird** [trebird/animal-rescue-website#2]
Hi @charlie-quinn,

Markbot is still having some issues with my adopt page, but seems fairly happy with everything else, as am I.

**Comment by trebird** [comment]
I would have loved the opportunity to continue tinkering and tighten up accessibility and form issues, but overall happy. Not sure how to grade this, but perhaps a B.

I've definitely learned how to work better with images (exporting, embed) and some accessibility, but need some more in-depth review of accessibility, forms and animations, which would have been fun to include.

**Comment by charlie-quinn** [comment]
✅ `This portion of your final assignment has been graded. A marking rubric has been sent to your gmail address.`

⚠️`Reminder: please close this issue once it has been resolved.`

**Comment by trebird** [comment]
Thank you so much for all your help this semester! Have a wonderful break and best of luck with all the wedding prep (congratulations)! 💕
